enableTransparentWorkspaces: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"

yarnPath: .yarn/releases/yarn-3.5.0.cjs

# This addresses some warnings about peer dependencies when you run `yarn`.
# @tiptap/starter-kit has an undeclared dependency on @tiptap/pm
# See https://github.com/ueberdosis/tiptap/issues/3746#issuecomment-1430129525
packageExtensions:
  "@tiptap/starter-kit@*":
    peerDependencies:
      "@tiptap/pm": "*"
