github_checks:
  annotations: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%  # allow for 2% reduction of coverage without failing

    # do not run coverage on patch nor changes
    patch: false