[tool.poetry]
name = "refstudio"
version = "0.1.0"
description = ""
authors = ["Greg Reda <gjreda+github@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9,<3.12"
grobid-tei-xml = "^0.1.3"
grobid-client-python = "^0.0.5"
importlib-metadata = "^6.6.0"
sentence-transformers = "^2.2.2"
lancedb = "^0.1.2"
wheel = "^0.40.0"

[tool.poetry.group.dev.dependencies]
pyinstaller = "^5.11.0"
ipython = "^8.13.2"
pytest = "^7.3.1"
ipdb = "^0.13.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
