/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * CliCommands(ingest: sidecar.typing.IngestResponse, rewrite: list[sidecar.typing.RewriteChoice])
 */
export interface CliSchema {
  ingest: IngestResponse;
  rewrite: RewriteChoice[];
}
/**
 * IngestResponse(project_name: str, references: list[sidecar.typing.Reference])
 */
export interface IngestResponse {
  project_name: string;
  references: Reference[];
}
/**
 * A reference for an academic paper / PDF
 */
export interface Reference {
  source_filename: string;
  filename_md5: string;
  title?: string;
  abstract?: string;
  contents?: string;
  authors?: Author[];
  chunks?: Chunk[];
  metadata?: {};
}
/**
 * Author(full_name: str, given_name: str, surname: str, email: str)
 */
export interface Author {
  full_name: string;
  given_name: string;
  surname: string;
  email: string;
}
/**
 * Chunk(text: str, vector: List[float] = <factory>, metadata: Dict[str, Any] = <factory>)
 */
export interface Chunk {
  text: string;
  vector?: number[];
  metadata?: {};
}
/**
 * RewriteChoice(index: int, text: str)
 */
export interface RewriteChoice {
  index: number;
  text: string;
}
