# Thanks to this blog post: https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions/
name: Build

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build Python binary
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest', 'windows-latest']
      
      steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
    
      - run: yarn python
      - uses: actions/upload-artifact@v3
        with:
          name: python-binary ${{ matrix.os }}
          path: src/bin/python/*
          if-no-files-found: error