# Thanks to this blog post: https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions/
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    # tags:
    #   - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  setup-python:
    name: Setup Python
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: ./.github/actions/setup-python
  
  build:
    name: Build Python binary
    needs: [setup-python]
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: ['macos-latest', 'windows-latest']
      
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: ./.github/actions/setup-python
    # - uses: actions/setup-python@v4
    #   with:
    #     python-version: "3.10"
  
    # - run: pip install pyinstaller
    - run: poetry run pyinstaller --noconfirm --distpath src-tauri/bin/python python/main.py
    - uses: actions/upload-artifact@v3
      with:
        name: python-binary
        path: src-tauri/bin/python/*
        if-no-files-found: error