name: Build and test sidecar binary

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'python/**'
      - 'package.json'

jobs:
  test-binary:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: Windows
            runner: windows-latest
          - name: Linx-x86_64
            runner: ubuntu-latest
          - name: macOS
            runner: macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - uses: ./.github/actions/setup-node
      - name: Create binary
        run: |
          yarn python
      - name: Start server and verify
        run: |
          ./src-tauri/bin/python/main/main serve &
          sleep 30
          curl -s http://0.0.0.0:1487/api/meta/status