name: WarmUp Node.js Environment

on:
  workflow_call:

jobs:
  warm-up-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-node
